# Generated by Django 3.1.2 on 2020-10-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
